### ISSUE TITLE
Release 0.6.3 no longer works with Helm 3.5.4

### ISSUE THREAD

**Issue by kerwinyoder** [localstack/helm-charts#94] opened 2023-09-01 21:20 UTC
Thanks for your work on this project! Unfortunately it appears 0.6.3 no longer works with older versions of Helm, specifically 3.5.4. Installing the chart causes the following parse error.

> Error: parse error at (localstack/charts/common/templates/_labels.tpl:14): unclosed action

The error does not occur on 0.6.2.

The [documentation](https://docs.localstack.cloud/references/localstack-on-kubernetes/) says LocalStack requires 3.2.0+. If this was an intentional change, you'll likely want to fix it. Otherwise, please update the documentation accordingly.

If you have difficult reproducing the problem or need additional information about my environment, please let me know. Thanks!

**Comment by alexrashed** [comment] 2023-09-04 10:24
Hi @kerwinyoder!
This seems to be related to the recent upgrade of our dependency on bitnami's common chart (https://github.com/localstack/helm-charts/pull/93).
It seems like the last release of the commons chart broke the compatibility.
Particularly this PR seems to introduce the incompatibility: https://github.com/bitnami/charts/pull/18154
The issue is already discussed in the PR and it currently has some traction (which makes me think that there might be a fix soon).
Is this blocking you currently? A simple workaround for now would be to upgrade to a newer version of Helm. I can verify that it works with the latest version of the `helm` CLI, but also that the issue is reproducible with `3.5.4`.

**Comment by alexrashed** [comment] 2023-09-05 08:18
It seems like this was a bit under the radar. I created https://github.com/bitnami/charts/issues/19011 to discuss this issue.
If this issue blocks you, we could also pin the `bitnami/common` version for now until this issue is resolved in the dependency.

**Closed** 2023-09-08 13:16 UTC
Labels: type: bug

**Comment by alexrashed** [comment] 2023-09-08 13:19
Hi @kerwinyoder!
This issue has been fixed in the `bitnami/common@2.10.1` (in https://github.com/bitnami/charts/pull/19177).
I just upgraded the lock file (in https://github.com/localstack/helm-charts/commit/f4526b4306904d43a38d3f98494d51c2ff903c29) and triggered a new release (`0.6.4`), so this issue should be resolved in the latest version.
Please let us know if you are still experiencing any issues. Thanks again for making us aware of this! 💯

**Comment by kerwinyoder** [comment] 2023-09-08 16:07
Hi @alexrashed 

I tested `0.6.4` and it works. Thanks for the quick fix! 🏆
