### ISSUE TITLE
Persistent volume mount directory needs to be updated for localstack v1.0.0

### ISSUE THREAD

**Issue by confusedpublic** [localstack/helm-charts#71] opened 2022-12-03 13:57 UTC
The [localstack v1.0.0 release](https://github.com/localstack/localstack/issues/6398) included a change to the directory where persistent data was stored from `/tmp/localstack` to `/var/lib/localstack`. However the `deployment.yml` was not updated to reflect this change: https://github.com/localstack/helm-charts/blob/ccf8d1e202537cb2be123236b5946d64b5d66461/charts/localstack/templates/deployment.yaml#L74

Thus if the helm chart is used with localstack >= v1.0.0, the chart will fail deploy with the following error reported in the pod's logs:

```
ERROR
============================================================================
  It seems you are mounting the LocalStack volume into /tmp/localstack.
  This will break the LocalStack container! Please update your volume mount
  destination to /var/lib/localstack.
  You can suppress this error by setting LEGACY_DIRECTORIES=1.

  See: https://github.com/localstack/localstack/issues/6398
============================================================================
```

This can be tested by:
* enabling persistence: `--set persistence.enabled=true`
* to cause the error:
  * setting `image.tag` to `latest` or a version >= `1.0.0`: `--set image.tag="1.2.0"
* to deploy successfully:
  *  setting `image.tag` to a a version < `1.0.0`: `--set image.tag="0.14.5"`

If persistence is set to `false` (the default value), then any version of localstack will deploy successfully.

**Comment by confusedpublic** [comment] 2022-12-03 14:27
Could this issue please be assigned to me? I've produced a fix in the linked PR.

**Comment by Rayyan98** [comment] 2022-12-04 14:08
Do we have a workaround for this meanwhile?

**Comment by alexrashed** [comment] 2022-12-05 09:16
FYI: This is a duplicate of #56 (just for documentation purposes 🙂).

**Closed** 2022-12-07 09:43 UTC
Labels: duplicate
