### ISSUE TITLE
Exception executing lambda (Go/NodeJS) in k8s

### ISSUE THREAD

**Issue by cmeans** [localstack/helm-charts#40] opened 2021-10-30 17:48 UTC
Using latest helm-chart 0.3.5

Installing into docker-desktop k8s with:
`helm install localstack localstack/localstack -n test --set lambdaExecutor=docker --set persistence.enabled=true --set mountDind.enabled=true --set service.type=ClusterIP`

Go lambda source:
```
package main

import (
	"context"

	"github.com/aws/aws-lambda-go/lambda"
)

func HandleRequest(ctx context.Context) (string, error) {
	return "Hello World!", nil
}

func main() {
	lambda.Start(HandleRequest)
}
```

Output from aws create-function:
```
{
    "FunctionName": "my-go-function",
    "FunctionArn": "arn:aws:lambda:us-east-2:000000000000:function:my-go-function",
    "Runtime": "go1.x",
    "Role": "arn:aws:iam::123456789012:role/lambda-ex",
    "Handler": "main",
    "CodeSize": 4446493,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-10-30T17:30:17.417+0000",
    "CodeSha256": "gItxIu47nrPCl9GHFHe0kAIZDILW6GFc0I2G/2FWG4A=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "4e33a774-0e06-4381-a0ad-63e3eea450c0",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}
```

Output from aws invoke:
```
{
    "errorMessage": "Lambda process returned with error. Result: . Output:\n",
    "errorType": "InvocationException",
    "stackTrace": [
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 770, in run_lambda\n    lock_discriminator=lock_discriminator,\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 336, in execute\n    return do_execute()\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 326, in do_execute\n    return _run(func_arn=func_arn)\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 157, in wrapped\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n    result = func(*args, **kwargs)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 313, in _run\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 299, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 587, in _execute\n    event=stdin, env_vars=environment, func_details=func_details\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 515, in run_lambda_executor\n    ) from error\n"
    ]
}
```

Console output from localstack:
[test-localstack-54659d9ffb-bpwb8-1635615368241129000.log](https://github.com/localstack/helm-charts/files/7447289/test-localstack-54659d9ffb-bpwb8-1635615368241129000.log)

Console output from dind:
[test-localstack-54659d9ffb-bpwb8-1635615782580850000.log](https://github.com/localstack/helm-charts/files/7447297/test-localstack-54659d9ffb-bpwb8-1635615782580850000.log)

Any idea what I might be doing wrong?

**Comment by LaikaN57** [comment] 2022-07-27 22:36
@cmeans The output from `aws lambda invoke` command is a bit truncated (in a way). If we trace that error back we can see the following in the provided localstack logs:

```
2021-10-30T17:32:20:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-2:000000000000:function:my-go-function: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 476, in run_lambda_executor
    func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 941, in execute_in_container
    command=command,
  File "/opt/code/localstack/localstack/utils/docker.py", line 1230, in create_container
    container = create_container()
  File "/opt/code/localstack/localstack/utils/docker.py", line 1213, in create_container
    return self.client().containers.create(
  File "/opt/code/localstack/localstack/utils/docker.py", line 860, in client
    raise ContainerException("Docker not available")
localstack.utils.docker.ContainerException: Docker not available

[...]
```

and if we look a bit further up in the log we see:

```
2021-10-30T17:32:20:INFO:localstack.services.awslambda.lambda_executors: Unable to get IP address of main Docker container "localstack_main": Docker not available
```

Is this still an issue?

If so, what version of Docker Desktop, `docker`, and k8s are you running?

I have not reproduced this yet, but hopefully this gives you some more clues as to what to look into for now.

**Comment by LaikaN57** [comment] 2022-07-27 22:37
@cmeans The output from `aws lambda invoke` command is a bit truncated (in a way). If we trace that error back we can see the following in the provided localstack logs:

```
2021-10-30T17:32:20:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-2:000000000000:function:my-go-function: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 476, in run_lambda_executor
    func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 941, in execute_in_container
    command=command,
  File "/opt/code/localstack/localstack/utils/docker.py", line 1230, in create_container
    container = create_container()
  File "/opt/code/localstack/localstack/utils/docker.py", line 1213, in create_container
    return self.client().containers.create(
  File "/opt/code/localstack/localstack/utils/docker.py", line 860, in client
    raise ContainerException("Docker not available")
localstack.utils.docker.ContainerException: Docker not available

[...]
```

and if we look a bit further up in the log we see:

```
2021-10-30T17:32:20:INFO:localstack.services.awslambda.lambda_executors: Unable to get IP address of main Docker container "localstack_main": Docker not available
```

Is this still an issue?

If so, what version of Docker Desktop, `docker`, and k8s are you running?

I have not reproduced this yet, but hopefully this gives you some more clues as to what to look into for now.

**Comment by cmeans** [comment] 2022-07-29 14:19
10 months later...

Is this still an issue?  Probably...I've ignored LocalStack in k8s given the slow support.

As all the apps involved have been updated multiple times over the past year or so..I'll have to find some time to retest.  If it's going to be another 10 months for a response, I'm not likely to revisit this soon.

Sadly, your feedback just confirmed what I already knew...the problem I could not solve was that though docker was running in it's own container (DinD) (confirmed in it's console), I could not get LocalStack to talk to it.

**Comment by LaikaN57** [comment] 2022-07-29 16:20
@cmeans ok I think the best thing to do here is going to be retest with the lastest helm chart (v0.4.x) to confirm we still have an issue (likely). Then, let's get some version numbers of your dind setup and related environment so I can try to reproduce as well.

I have not played around with dind, k8s, and localstack, all together yet, but I am happy to dive in and help debug.

Alternatively, if this is not causing any impact, you can just close this issue as a "won't fix" for now and re-open or open a new ticket when ready to attempt again.

**Comment by ross-grinvalds** [comment] 2022-07-29 20:42
@cmeans, just getting started loading LocalStack into a KIND cluster for our own testing. It is disappointing to see you haven't had any additional support over the past 10 months, as we are also having issues when trying to invoke Lambda functions 😞. I will be doing more troubleshooting next week and will try to get back with you if we are able to break through and get something working.

**Comment by LaikaN57** [comment] 2022-07-29 20:47
@ross-grinvalds are you having the same issue? If so, can you post some version numbers and env configs. If not, can you do so in a new issue.

**Comment by cmeans** [comment] 2022-07-31 01:18
Thanks @LaikaN57 !

It appears to be working fine in the latest version of localstack (same version of the dind image).

```
START 809262d7-4278-41a0-a81b-cd806f1bbf47: Lambda arn:aws:lambda:us-east-2:000000000000:function:my-go-function started via "local" executor ...
START RequestId: 27231747-1516-1098-8172-66dd706a9080 Version: $LATEST
END RequestId: 27231747-1516-1098-8172-66dd706a9080
REPORT RequestId: 27231747-1516-1098-8172-66dd706a9080  Init Duration: 3000.00 ms       Duration: 28.09 ms Billed Duration: 29 ms  Memory Size: 1536 MB    Max Memory Used: 487 MB
END RequestId: 809262d7-4278-41a0-a81b-cd806f1bbf47
REPORT RequestId: 809262d7-4278-41a0-a81b-cd806f1bbf47 Duration: 80000 ms

```

I did have to drop the `lambdaExecutor` override.

**Comment by cmeans** [comment] 2022-07-31 15:08
This testing has been performed against my local Docker Kubernetes.  Next is to test in the target environment, which is Amazon EKS.  Will follow-up once I've had time to test there.

**Comment by cmeans** [comment] 2022-07-31 17:02
@LaikaN57 

Now testing against Amazon EKS, which is failing, it also appears that the first test with local Docker Kubernetes wasn't working the way I expected.

Comparing the dind container logs between the two environments, there's no additional entries with the Docker Kubernetes instance after:

`API listen on :2376`

Whereas in the Amazon EKS environment, I do see additional entries...which implies to me that Docker Kubernetes was using the local Docker and not the `dind` container.

Here's the logs from the localstack container in Amazon EKS:
```
WARNING
============================================================================
  It seems you are mounting the LocalStack volume into /tmp/localstack.
  This will break the LocalStack container! Please update your volume mount
  destination to /var/lib/localstack. In the meantime, we have set
  LEGACY_DIRECTORIES=1, to make LocalStack behave as in <1.0.0, and which
  should prevent any serious issues, but will be removed soon!
  You can suppress this warning by setting LEGACY_DIRECTORIES=1

  See: https://github.com/localstack/localstack/issues/6398
============================================================================

Waiting for all LocalStack services to be ready
2022-07-31 16:26:07,324 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-07-31 16:26:07,326 INFO supervisord started with pid 17
2022-07-31 16:26:08,329 INFO spawned: 'infra' with pid 22
SERVICES variable is ignored if EAGER_SERVICE_LOADING=0.
2022-07-31 16:26:09,558 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 1.0.4.dev
LocalStack build date: 2022-07-30
LocalStack build git hash: 736e7ad4

2022-07-31T16:26:09.756  WARN --- [  Thread-106] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-07-31T16:26:09.756  WARN --- [  Thread-106] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-07-31T16:26:09.757  INFO --- [  Thread-106] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-07-31T16:26:09.757  INFO --- [  Thread-106] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
2022-07-31T16:33:15.072  INFO --- [   asgi_gw_1] localstack.services.infra  : Starting mock Lambda service on http port 4566 ...
2022-07-31T16:33:15.626  INFO --- [   asgi_gw_1] localstack.utils.bootstrap : Execution of "require" took 1073.40ms
2022-07-31T16:33:16.173  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS lambda.CreateFunction => 200
2022-07-31T16:33:24.617  INFO --- [uest_thread)] l.s.a.lambda_executors     : Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-2:000000000000:function:my-go-function"
2022-07-31T16:33:24.619  INFO --- [uest_thread)] l.u.container_networking   : Unable to get network name of main container "localstack_main": localstack_main
2022-07-31T16:33:24.620  INFO --- [uest_thread)] l.u.container_networking   : Unable to get IP address of main Docker container "localstack_main": localstack_main
2022-07-31T16:33:24.620  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:us-east-2:000000000000:function:my-go-function
2022-07-31T16:33:38.837  INFO --- [uest_thread)] l.s.a.lambda_executors     : writing log to file '/tmp/localstack/lambda_tgr0fjbx.log'
2022-07-31T16:33:38.887  INFO --- [uest_thread)] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:us-east-2:000000000000:function:my-go-function: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 638, in run_lambda_executor
    result, log_output = self.execute_in_container(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1266, in execute_in_container
    return DOCKER_CLIENT.start_container(
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 462, in start_container
    stdout, stderr = self._read_from_sock(sock, False)
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 66, in _read_from_sock
    raise ContainerException("Invalid frame type when reading from socket")
localstack.utils.container_utils.container_client.ContainerException: Invalid frame type when reading from socket

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 543, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 465, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 455, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 167, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 163, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 442, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 438, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 761, in _execute
    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 683, in run_lambda_executor
    raise InvocationException(
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:
```

Here's the logs from the dind container in Amazon EKS:
```
Generating RSA private key, 4096 bit long modulus (2 primes)
.......................................................++++
.................................................................................++++
e is 65537 (0x010001)
Generating RSA private key, 4096 bit long modulus (2 primes)
..........................................................................................................++++
.....................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind server
Getting CA Private Key
/opt/docker/tls/server/cert.pem: OK
Generating RSA private key, 4096 bit long modulus (2 primes)
.................................++++
...........................................................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind client
Getting CA Private Key
/opt/docker/tls/client/cert.pem: OK
time="2022-07-31T16:25:41.463903603Z" level=info msg="Starting up"
time="2022-07-31T16:25:41.465209039Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
time="2022-07-31T16:25:41.466243016Z" level=info msg="libcontainerd: started new containerd process" pid=63
time="2022-07-31T16:25:41.466282671Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-07-31T16:25:41.466293130Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2022-07-31T16:25:41.466322338Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
time="2022-07-31T16:25:41.466345205Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2022-07-31T16:25:41Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
time="2022-07-31T16:25:41.483146052Z" level=info msg="starting containerd" revision=10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1 version=v1.6.6
time="2022-07-31T16:25:41.497309773Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
time="2022-07-31T16:25:41.497520692Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.aufs\"..." type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.501628586Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exit status 1 \"ip: can't find device 'aufs'\\nmodprobe: can't change directory to '/lib/modules': No such file or directory\\n\"): skip plugin" type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.501696756Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.501959313Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs (xfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.501978658Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.devmapper\"..." type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.501994143Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
time="2022-07-31T16:25:41.502009985Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.502072052Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.overlayfs\"..." type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.502222685Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.zfs\"..." type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.502388216Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2022-07-31T16:25:41.502408619Z" level=info msg="loading plugin \"io.containerd.metadata.v1.bolt\"..." type=io.containerd.metadata.v1
time="2022-07-31T16:25:41.502455113Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
time="2022-07-31T16:25:41.502472059Z" level=info msg="metadata content store policy set" policy=shared
time="2022-07-31T16:25:41.506521580Z" level=info msg="loading plugin \"io.containerd.differ.v1.walking\"..." type=io.containerd.differ.v1
time="2022-07-31T16:25:41.506575510Z" level=info msg="loading plugin \"io.containerd.event.v1.exchange\"..." type=io.containerd.event.v1
time="2022-07-31T16:25:41.506593667Z" level=info msg="loading plugin \"io.containerd.gc.v1.scheduler\"..." type=io.containerd.gc.v1
time="2022-07-31T16:25:41.506643999Z" level=info msg="loading plugin \"io.containerd.service.v1.introspection-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.506662216Z" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.506681486Z" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.506699109Z" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.506724537Z" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.506970128Z" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.506989440Z" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.507005928Z" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.507023562Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
time="2022-07-31T16:25:41.507170556Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
time="2022-07-31T16:25:41.507288180Z" level=info msg="loading plugin \"io.containerd.monitor.v1.cgroups\"..." type=io.containerd.monitor.v1
time="2022-07-31T16:25:41.507649700Z" level=info msg="loading plugin \"io.containerd.service.v1.tasks-service\"..." type=io.containerd.service.v1
time="2022-07-31T16:25:41.507691427Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507714723Z" level=info msg="loading plugin \"io.containerd.internal.v1.restart\"..." type=io.containerd.internal.v1
time="2022-07-31T16:25:41.507777574Z" level=info msg="loading plugin \"io.containerd.grpc.v1.containers\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507791931Z" level=info msg="loading plugin \"io.containerd.grpc.v1.content\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507809624Z" level=info msg="loading plugin \"io.containerd.grpc.v1.diff\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507819326Z" level=info msg="loading plugin \"io.containerd.grpc.v1.events\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507834797Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507855904Z" level=info msg="loading plugin \"io.containerd.grpc.v1.images\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.507875780Z" level=info msg="loading plugin \"io.containerd.grpc.v1.leases\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.508775042Z" level=info msg="loading plugin \"io.containerd.grpc.v1.namespaces\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.508839579Z" level=info msg="loading plugin \"io.containerd.internal.v1.opt\"..." type=io.containerd.internal.v1
time="2022-07-31T16:25:41.508991662Z" level=info msg="loading plugin \"io.containerd.grpc.v1.snapshots\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.509020898Z" level=info msg="loading plugin \"io.containerd.grpc.v1.tasks\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.509066089Z" level=info msg="loading plugin \"io.containerd.grpc.v1.version\"..." type=io.containerd.grpc.v1
time="2022-07-31T16:25:41.509091307Z" level=info msg="loading plugin \"io.containerd.tracing.processor.v1.otlp\"..." type=io.containerd.tracing.processor.v1
time="2022-07-31T16:25:41.509117987Z" level=info msg="skip loading plugin \"io.containerd.tracing.processor.v1.otlp\"..." error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1
time="2022-07-31T16:25:41.509136940Z" level=info msg="loading plugin \"io.containerd.internal.v1.tracing\"..." type=io.containerd.internal.v1
time="2022-07-31T16:25:41.509157761Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
time="2022-07-31T16:25:41.509433504Z" level=info msg=serving... address=/var/run/docker/containerd/containerd-debug.sock
time="2022-07-31T16:25:41.509521863Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock.ttrpc
time="2022-07-31T16:25:41.509765619Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock
time="2022-07-31T16:25:41.509798816Z" level=info msg="containerd successfully booted in 0.027365s"
time="2022-07-31T16:25:41.519422216Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-07-31T16:25:41.519445902Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2022-07-31T16:25:41.519467901Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
time="2022-07-31T16:25:41.519480529Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2022-07-31T16:25:41.521744375Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-07-31T16:25:41.521762997Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2022-07-31T16:25:41.521776666Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
time="2022-07-31T16:25:41.521798216Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2022-07-31T16:25:41.535296480Z" level=warning msg="Your kernel does not support cgroup blkio weight"
time="2022-07-31T16:25:41.535314590Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
time="2022-07-31T16:25:41.535463979Z" level=info msg="Loading containers: start."
time="2022-07-31T16:25:41.573736073Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2022-07-31T16:25:41.597296933Z" level=info msg="Loading containers: done."
time="2022-07-31T16:25:41.603917204Z" level=info msg="Docker daemon" commit=a89b842 graphdriver(s)=overlay2 version=20.10.17
time="2022-07-31T16:25:41.604032336Z" level=info msg="Daemon has completed initialization"
time="2022-07-31T16:25:41.623791317Z" level=info msg="API listen on /var/run/docker.sock"
time="2022-07-31T16:25:41.630964274Z" level=info msg="API listen on [::]:2376"
time="2022-07-31T16:33:38.570759068Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-07-31T16:33:38.570811057Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-07-31T16:33:38.570832269Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-07-31T16:33:38.571070122Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/fb8a4ddfa1c2a9a19266b2004b43fb70b04e309ddcdc1d7f18b0af4609d31fd8 pid=251 runtime=io.containerd.runc.v2
time="2022-07-31T16:33:38.830470581Z" level=info msg="ignoring event" container=fb8a4ddfa1c2a9a19266b2004b43fb70b04e309ddcdc1d7f18b0af4609d31fd8 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
time="2022-07-31T16:33:38.830604924Z" level=info msg="shim disconnected" id=fb8a4ddfa1c2a9a19266b2004b43fb70b04e309ddcdc1d7f18b0af4609d31fd8
time="2022-07-31T16:33:38.830665867Z" level=warning msg="cleaning up after shim disconnected" id=fb8a4ddfa1c2a9a19266b2004b43fb70b04e309ddcdc1d7f18b0af4609d31fd8 namespace=moby
time="2022-07-31T16:33:38.830684364Z" level=info msg="cleaning up dead shim"
time="2022-07-31T16:33:38.848296354Z" level=warning msg="cleanup warnings time=\"2022-07-31T16:33:38Z\" level=info msg=\"starting signal loop\" namespace=moby pid=322 runtime=io.containerd.runc.v2\n"
```

I've not had the chance to go through the logs in detail myself yet, but welcome feedback/suggestions.

**Comment by alexrashed** [comment] 2023-05-11 07:25
Hi @cmeans!
I'm really sorry about the late answer. A lot has changed since you experienced your issues, and with v2 LocalStack's Lambda provider has been completely rewritten.
Could you maybe give the latest version of the chart and LocalStack another try and see if this issue still exists?
Thanks!

**Comment by alexrashed** [comment] 2023-06-19 12:16
I'll close this issue for now, please open a new issue if you are still experiencing this issue.

**Closed by alexrashed** 2023-06-19 12:16 UTC
Labels: type: bug, status: response required
